using UnityEngine;


namespace Drone.Stability
{
    /// <summary>
    /// Collection of settings for drone movements and stabilization. Can be stored as an asset.
    /// </summary>
    [CreateAssetMenu(menuName = "Drone Settings/Drone Control Settings", fileName = "DroneControlSettings")]
    public class DroneControlSettings : ScriptableObject
    {
        [Header("Throttle and Torque")]
        [Range(0f, 10f)]
        [Tooltip("Max target vertical speed of the drone when using stabilization (meters per second).")]
        public float maxLiftSpeed = 5;

        [Range(0f, 100f)]
        [Tooltip(
            "Max lift force generated by single drone motor in newtons. Larger values mean that drone will reach target speed faster."
        )]
        public float maxLiftForce = 30;

        [Range(0f, 1f)]
        [Tooltip("Max torque generated by single drone motor.")]
        public float torqueMultiplier = 0.005f;

        [Tooltip("Throttle PID controller's parameters. I factor must be greater than 0 to compensate gravity.")]
        public PidParameters pidThrottle = new(1, 0.7f, 0.01f);


        [Header("Pitch")]
        [Range(0f, 60f)]
        [Tooltip("Max pitch angle (X axis rotation) in degrees when using stabilization.")]
        public float maxPitchAngle = 20;

        [Range(0f, 1f)]
        [Tooltip(
            "Max pitch force component value. Must be in range [0, 1]. Larger values mean that drone will reach target pitch angle faster."
        )]
        public float maxPitchForce = 0.25f;

        [Tooltip("Pitch PID controller's parameters.")]
        public PidParameters pidPitch = new(1, 0.1f, 0.01f);


        [Header("Yaw")]
        [Range(0f, 60f)]
        [Tooltip("Max yaw rotation speed (Y axis rotation) in degrees per second when using stabilization.")]
        public float maxYawSpeed = 2f;

        [Range(0f, 1f)]
        [Tooltip(
            "Max yaw force component value. Must be in range [0, 1]. Larger values mean that drone will reach target yaw speed faster."
        )]
        public float maxYawForce = 0.1f;

        [Tooltip("Yaw PID controller's parameters.")]
        public PidParameters pidYaw = new(1, 0.1f, 0.01f);


        [Header("Roll")]
        [Range(0f, 60f)]
        [Tooltip("Max roll angle (Z axis rotation) in degrees when using stabilization.")]
        public float maxRollAngle = 20;

        [Range(0f, 1f)]
        [Tooltip(
            "Max yaw force component value. Must be in range [0, 1]. Larger values mean that drone will reach target roll angle faster."
        )]
        public float maxRollForce = 0.25f;

        [Tooltip("Roll PID controller's parameters.")]
        public PidParameters pidRoll = new(1, 0.1f, 0.001f);


        private void OnValidate()
        {
            // PID output always clamped
            pidThrottle.minOutput = -maxLiftForce;
            pidThrottle.maxOutput = maxLiftForce;

            pidPitch.SetClamping(maxPitchForce);
            pidYaw.SetClamping(maxYawForce);
            pidRoll.SetClamping(maxRollForce);
        }
    }
}