using UnityEngine;


namespace Drone.Stability
{
    /// <summary>
    /// Collection of settings for drone movements and stabilization. Can be stored as an asset.
    /// </summary>
    [CreateAssetMenu(menuName = "Drone Settings/Drone Control Settings", fileName = "DroneControlSettings")]
    public class DroneControlSettings : ScriptableObject
    {
        [Tooltip("Max target vertical speed of the drone when using stabilization (meters per second).")]
        [Header("Throttle and Torque")]
        [Range(0f, 10f)] public float maxLiftSpeed = 5;
        
        [Tooltip("Max lift force generated by single drone motor in newtons. Larger values mean that drone will reach target speed faster.")]
        [Range(0f, 100f)] public float maxLiftForce = 30;
       
        [Tooltip("Max torque generated by single drone motor.")]
        [Range(0f, 1f)]  public float torqueMultiplier = 0.005f;
        
        [Tooltip("Throttle PID controller's parameters. I factor must be greater than 0 to compensate gravity.")]
        public PidParameters pidThrottle = new(1, 0.7f, 0.01f);

        
        [Tooltip("Max pitch angle (X axis rotation) in degrees when using stabilization.")]
        [Header("Pitch")]
        [Range(0f, 60f)] public float maxPitchAngle = 20;
        
        [Tooltip("Max pitch force component value. Must be in range [0, 1]. Larger values mean that drone will reach target pitch angle faster.")]
        [Range(0f, 1f)]  public float maxPitchForce = 0.25f;
        
        [Tooltip("Pitch PID controller's parameters.")]
        public PidParameters pidPitch = new(1, 0.1f, 0.01f);
        
        
        [Tooltip("Max yaw rotation speed (Y axis rotation) in degrees per second when using stabilization.")]
        [Header("Yaw")]
        [Range(0f, 60f)] public float maxYawSpeed = 2f;
        
        [Tooltip("Max yaw force component value. Must be in range [0, 1]. Larger values mean that drone will reach target yaw speed faster.")]
        [Range(0f, 1f)]  public float maxYawForce = 0.1f;
        
        [Tooltip("Yaw PID controller's parameters.")]
        public PidParameters pidYaw = new(1, 0.1f, 0.01f);
        
        
        [Tooltip("Max roll angle (Z axis rotation) in degrees when using stabilization.")]
        [Header("Roll")]
        [Range(0f, 60f)] public float maxRollAngle = 20;
        
        [Tooltip("Max yaw force component value. Must be in range [0, 1]. Larger values mean that drone will reach target roll angle faster.")]
        [Range(0f, 1f)] public float maxRollForce = 0.25f;
       
        [Tooltip("Roll PID controller's parameters.")]
        public PidParameters pidRoll = new (1, 0.1f, 0.001f);

        
        private void OnValidate()
        {
            // PID output always clamped
            pidThrottle.minOutput = -maxLiftForce;
            pidThrottle.maxOutput = maxLiftForce;

            pidPitch.SetClamping(maxPitchForce);
            pidYaw.SetClamping(maxYawForce);
            pidRoll.SetClamping(maxRollForce);
        }
    }
}