using System;
using UnityEngine;


namespace Drone
{
    [Serializable]
    public struct DroneControlParams
    {
        /// <summary>Max vertical velocity of the drone when using stabilization.</summary>
        [Range(0f, 10f)] public float maxLiftSpeed;
        /// <summary>Max lift force value.</summary>
        [Range(0f, 10f)] public float forceMultiplier;
        /// <summary>Max torque generated by drone motors.</summary>
        [Range(0f, 10f)] public float torqueMultiplier;

        /// <summary>Max pitch angle (X axis rotation) in degrees when using stabilization.</summary>
        [Range(0f, 60f)] public float maxPitchAngle;
        /// <summary>Max pitch force component value. Must be in range [0, 1].</summary>
        [Range(0f, 1f)]  public float maxPitchForce;

        /// <summary>Max yaw angle (Y axis rotation) in degrees when using stabilization.</summary>
        [Range(0f, 60f)] public float maxYawAngle;
        /// <summary>Max yaw force component value. Must be in range [0, 1].</summary>
        [Range(0f, 1f)]  public float maxYawForce;

        /// <summary>Max roll angle (Z axis rotation) in degrees when using stabilization.</summary>
        [Range(0f, 60f)] public float maxRollAngle;
        /// <summary>Max yaw force component value. Must be in range [0, 1].</summary>
        [Range(0f, 1f)]  public float maxRollForce;

        
        public DroneControlParams(float maxLiftSpeed, float forceMultiplier, float maxPitchAngle = 15f, float maxYawAngle = 15f, float maxRollAngle = 15f)
        {
            this.maxLiftSpeed = maxLiftSpeed;
            this.forceMultiplier = forceMultiplier;
            this.torqueMultiplier = 0.01f;
            this.maxPitchAngle = maxPitchAngle;
            this.maxPitchForce = 0.5f;
            this.maxYawAngle = maxYawAngle;
            this.maxYawForce = 0.5f;
            this.maxRollAngle = maxRollAngle;
            this.maxRollForce = 0.5f;
        }

        /// <summary>Create default parameters with pitch/yaw/roll angles of 15 degrees.</summary>
        public static DroneControlParams Default => new()
        {
            maxLiftSpeed = 5f,
            forceMultiplier = 5f,
            torqueMultiplier = 0.01f,
            maxPitchAngle = 15f,
            maxPitchForce = 0.5f,
            maxYawAngle = 15f,
            maxYawForce = 0.5f,
            maxRollAngle = 15f,
            maxRollForce = 0.5f
        };
    }
}